
spring:
  application:
    name: taco-cloud


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


  datasource:
    generate-unique-name: false
    name: tacocloud

    # : H2 Console:
    #????????? ?? ?????? http://localhost:8080/h2-console
    #? ???????????? ? ???? ?????? H2, ????? ????????? ?????????? ??????.
    # ??????????? ????????? ???????????:
    #
    #JDBC URL: jdbc:h2:mem:tacocloud
    #User Name: sa
    #Password: ???????? ?????? (?? ?????????)


 # logging:
  #level:
   # root: DEBUG

